[package]
name = "daily_strip"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.75"
async-trait = "0.1.74"
cached = {version = "0.51.3", features = ["default", "async"]}
eframe = "0.27.2"
egui_extras = {version = "0.27.2", features = ["default", "all_loaders"] }
image = { version = "0.24", features = ["jpeg", "png"] } 
rand = "0.8.5"
reqwest = "0.12.4"
rss = "2.0.6"
scraper = "0.19.0"
strum = "0.26.2"
strum_macros = "0.26.2"
thiserror = "1.0.50"
tokio = { version = "1.33.0", features = ["macros", "rt-multi-thread"]}

[workspace]
